# Generated by Django 5.2.14 on 2026-05-30 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('founding_year', models.DateField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('IMDB', models.CharField(max_length=100)),
                ('release_year', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci Fi'), ('Documentary', 'Documentary'), ('Animated', 'Animated')])),
                ('type', models.CharField(choices=[('Digital', 'Digital'), ('Blu-Ray', 'Blu Ray'), ('DVD', 'Dvd')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('production_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='myapp.productionhouse')),
            ],
        ),
    ]
